baseURL = "https://rodp.me/"
title = "Rodrigo Pizzolato"
theme = "hextra"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
enableGitInfo = true

languageCode = "en-US"

canonifyURLs = false

[pagination]
pagerSize = 10