[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Resume"
pageRef = "/resume"
weight = 2

[[main]]
name = "Articles"
pageRef = "/articles"
weight = 3

[[main]]
name = "About"
pageRef = "/about"
weight = 4

[[main]]
name =