[[main]]
name = "Home"
url = "/en/"
weight = 1

[[main]]
name = "Resume"
url = "/en/resume/"
weight = 2

[[main]]
name = "Articles"
url = "/en/articles/"
weight = 3

[[main]]
name = "About"
url = "/en/about/"
weight = 4